[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
dotenv = ".env.test"

eth_rpc_url = "https://ethereum-rpc.publicnode.com"
bsc_rpc_url = "https://bsc-rpc.publicnode.com"
polygon_rpc_url = "https://polygon-rpc.publicnode.com"

# Optimizer settings
optimizer = true
optimizer_runs = 200

# Additional settings for testing
gas_limit = 9223372036854775807
gas_price = 20000000000

# Fuzz testing configuration
fuzz = { runs = 1000 }

# Coverage settings
[profile.coverage]
match_coverage = "src/**/*.sol"

remappings = [
  "UniV2/=lib/UniV2/contracts/",
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  "forge-std/=lib/forge-std/src/",
  "v3-core/=lib/v3-core/",
  "@uniswap/v3-core/=lib/v3-core/",
  "v3-periphery/=lib/v3-periphery/",
  "@uniswap/v3-periphery/=lib/v3-periphery/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
